package com.telefonica.talentum.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Usuario service. Represents a row in the &quot;LibreriaLiferay_Usuario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.telefonica.talentum.model.impl.UsuarioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.telefonica.talentum.model.impl.UsuarioImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Usuario
 * @see com.telefonica.talentum.model.impl.UsuarioImpl
 * @see com.telefonica.talentum.model.impl.UsuarioModelImpl
 * @generated
 */
public interface UsuarioModel extends BaseModel<Usuario>, GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a usuario model instance should use the {@link Usuario} interface instead.
     */

    /**
     * Returns the primary key of this usuario.
     *
     * @return the primary key of this usuario
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this usuario.
     *
     * @param primaryKey the primary key of this usuario
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the user ID of this usuario.
     *
     * @return the user ID of this usuario
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this usuario.
     *
     * @param userId the user ID of this usuario
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this usuario.
     *
     * @return the user uuid of this usuario
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this usuario.
     *
     * @param userUuid the user uuid of this usuario
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the group ID of this usuario.
     *
     * @return the group ID of this usuario
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this usuario.
     *
     * @param groupId the group ID of this usuario
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this usuario.
     *
     * @return the company ID of this usuario
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this usuario.
     *
     * @param companyId the company ID of this usuario
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user name of this usuario.
     *
     * @return the user name of this usuario
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this usuario.
     *
     * @param userName the user name of this usuario
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this usuario.
     *
     * @return the create date of this usuario
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this usuario.
     *
     * @param createDate the create date of this usuario
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this usuario.
     *
     * @return the modified date of this usuario
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this usuario.
     *
     * @param modifiedDate the modified date of this usuario
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.telefonica.talentum.model.Usuario usuario);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.telefonica.talentum.model.Usuario> toCacheModel();

    @Override
    public com.telefonica.talentum.model.Usuario toEscapedModel();

    @Override
    public com.telefonica.talentum.model.Usuario toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
